GET http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Blog 1",
    "author": "User",
    "url": "https://www.userblog.com",
    "likes": 1
}